General:
    comment: 
    seed: 2021
    fp16: True
    amp_level: O2
    precision: 16 
    multi_gpu_mode: dp
    gpus: [0,1]
    epochs: &epoch 200 
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: test #train #test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: False
    #data_dir: /mnt/usb2/beijing2_feat/
    # data_dir: /home/stat-caolei/code/SVS_SLIDES/CLAM/beijing_feat_34/
    #data_dir: /mnt/usb3/beijing2_feat/
    data_dir: /home/stat-caolei/code/SVS_SLIDES/CLAM/tcga_dx_feat/
    #label_dir: dataset_csv/beijing2/
    #label_dir: dataset_csv/beijing/
    #label_dir: dataset_csv/beijing2/
    #label_dir: dataset_csv/diff_I/
    # label_dir: dataset_csv/diff_II/
    label_dir: dataset_csv/diff_III/
    fold: 4
    nfold: 5

    train_dataloader:
        batch_size: 1 
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 2


Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

